version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
        - echo "This is pre build phase"
  build:
    commands:
    - echo "This is build phase"
    # - mvn clean prepare-package war:exploded
    - mvn package
    - mv target/Hello_SpringBoot_With_War-0.0.1-SNAPSHOT.war    Hello_SpringBoot_With_War-0.0.1-SNAPSHOT.war
  post_build:
    commands:
    - echo "This is post-build phase"
    - mv target/deploy ./
artifacts:
  files:
    # - target/deploy/**/*
     - Hello_SpringBoot_With_War-0.0.1-SNAPSHOT.war
     
  base-directory: 'target/Hello_SpringBoot_With_War'

  